; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rymcu-esp32-s3-devkitc-1]
platform = espressif32
board = rymcu-esp32-s3-devkitc-1
framework = arduino
lib_deps =
    Bodmer/TFT_eSPI@^2.4.70
    lvgl/lvgl@^9.2.2
build_flags = -I$PROJECT_DIR/include/lvgl -I$PROJECT_DIR/include/TFT_eSPI -DLV_CONF_INCLUDE_SIMPLE
monitor_speed = 115200
